def distinct_powers(ceiling):
    """
    Returns the number of distinct terms in the sequence generated by a^b for
    2 <= a, b, <= ceiling.
    """
    powerset = set()
    for a in range(2, ceiling + 1):
        for b in range(2, ceiling + 1):
            powerset.add(a**b)
    return len(powerset)


def solve(vol=0):
    return distinct_powers(100)
